; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = dfrobot_firebeetle2_esp32e
default_envs = dfrobot_firebeetle2_esp32e_prod
;default_envs = firebeetle32

; default options for each '[env:**]'
[env]
platform = espressif32 @ 7.0.0
;platform = espressif32 @ 6.13.0
;;;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
build_unflags = '-std=gnu++11'
build_flags = '-Wall' '-std=gnu++17'
lib_deps =
  adafruit/Adafruit BMP280 Library @^3.0.0
  adafruit/Adafruit BME280 Library @ 2.3.0
  adafruit/Adafruit BME680 Library @ 2.0.6
  adafruit/Adafruit BusIO @ 1.17.4
  adafruit/Adafruit Unified Sensor @ 1.1.15
  bblanchon/ArduinoJson @ 7.4.3
  zinggjm/GxEPD2 @ 1.6.8
  tzapu/WiFiManager @ ^2.0.17


[env:dfrobot_firebeetle2_esp32e_prod]
board = dfrobot_firebeetle2_esp32e
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
board_build.f_cpu = 80000000L


[env:dfrobot_firebeetle2_esp32e]
board = dfrobot_firebeetle2_esp32e
framework = arduino
board_build.partitions = huge_app.csv

; Protocolli per ESP-PROG
upload_protocol = esp-prog

debug_speed = 1000

; Configurazione per debug esterno
debug_tool = custom
debug_port = localhost:3333
debug_init_break = tbreak setup

; Comandi per collegarsi a OpenOCD già attivo
debug_init_cmds =
  target extended-remote $DEBUG_PORT
  $LOAD_CMD
  $INIT_BREAK
;debug_extra_cmds = 
;  set remote hardware-watchpoint-limit 2

; Ottimizzazione per debug (riduce la dimensione ed evita che il debugger "salti" righe)
;debug_build_flags = -Og -g3 -ggdb



[env:firebeetle32]
board = firebeetle32
monitor_speed = 115200
; override default partition table
; https://github.com/espressif/arduino-esp32/tree/master/tools/partitions
board_build.partitions = huge_app.csv
; change MCU frequency, 240MHz -> 80MHz (for better power efficiency)
board_build.f_cpu = 80000000L
;for serial Port


;for debugging and upload
debug_tool = esp-prog
upload_protocol = esp-prog
debug_init_break = tbreak setup
debug_build_flags = -Og -g2 -ggdb2

